#include <QString>

struct Action{
    int id;
    QString name;

};

static const QString EventAI_Actions[][]{
{"NONE",                    "","","","Does nothign"},
{"TEXT",                    "-TextId","-TextId","-TextId","Simply displays the specified -TextId. When -TextId2 and -TextId3 are specified, the selection will be randomized. Text types are defined, along with other options for the text, in a table below. All values needs to be negative."},
{"SET_FACTION",             "FactionId","TempFactionFlag","","Changes faction for a creature. When param1 is zero, creature will revert to it's default faction. Flags will determine when faction is restored to default (evade, respawn etc)"},
{"MORPH_TO_MODEL_OR_ENTRY", "CreatureEntry","ModelId","","Set either model from creature_template.entry (Param1) OR explicit modelId (Param2). If (Param1) AND (Param2) are both 0, demorph and revert to the default model."},
{"SOUND",                   "SoundId","","","Plays Sound"},
{"EMOTE",                   "EmoteId","","","Does emote"},
{"RANDOM_SAY",              "","","","Not implemented in core"},
{"RANDOM_YELL",             "","","","Not implemented in core"},
{"RANDOM_TEXTEMOTE",        "","","","Not implemented in core"},
{"RANDOM_SOUND",            "SoundId1","SoundId2","SoundId3","Plays random sound between 3 params*"},
{"RANDOM_EMOTE",            "EmoteId1","EmoteId2","EmoteId3","Emotes random emote between 3 params"},
{"CAST",                    "SpellId","Target","CastFlags","Casts spell (param1) on target type (param2). Uses Cast Flags (specified below target types)"},
{"SUMMON",                  "CreatureID","Target","Duration","Summons creature (param1) to attack target (param2) for (param3) duration. Spawns on top of current creature."},
{"THREAT_SINGLE_PCT",       "Threat%","Target","","Modifies threat by (param1) on target type (param2)"},
{"THREAT_ALL_PCT",          "Threat%","",""," Modifies threat by (param1) on all targets (using -100% on all will result in full aggro dump)"},
{"QUEST_EVENT",             "QuestID","Target","","Calls AreaExploredOrEventHappens with (param1) for target type (Param2)"},
{"QUEST_CASTCREATUREGO",    "QuestID","SpellId","Target","Sends CastCreatureOrGo for Quest (param1) with SpellId (param2) for target (param3)"},
{"SET_UNIT_FIELD",          "Field_Number","Value","Target","Sets Unit Field (param1) to Value (param2) on target type (param3)"},
{"SET_UNIT_FLAG",           "Flags","Target","","Sets flag (flags can be binary OR together to modify multiple flags at once) on for Target type (param2)"},
{"REMOVE_UNIT_FLAG",        "Flags","Target","","Removes flag (flags can be binary OR together to modify multiple flags at once) on for Target type (param2)"},
{"AUTO_ATTACK",             "AllowAutoAttack","","","0 = stop melee attack, anything else means continue attacking/allow melee attacking"},
{"COMBAT_MOVEMENT",         "AllowCombatMove","StopMeleeCombat","","0 = stop combat based movement, anything else continue/allow combat based movement (targeted movement generator)"},
{"SET_PHASE","Phase",       "","","Sets the current phase to (param1)"},
{"INC_PHASE","Value",       "","","Increments the phase by (param1). May be negative to decrement phase but should not be 0."},
{"EVADE",                   "","","","Forces the creature to evade. Wiping all threat and dropping combat."},
{"FLEE",                    "","","","Causes the creature to flee. Please use this action instead of directly casting this spell so we may change this when a more correct approach is found."},
{"QUEST_EVENT_ALL",         "QuestId","","","Calls GroupEventHappens with (param1). Only used if it's _expected_ event should complete for all players in current party"},
{"CASTCREATUREGO_ALL",      "QuestId","SpellId","","Calls CastedCreatureOrGo for all players on the threat list with QuestID(Param1) and SpellId(Param2)"},
{"REMOVEAURASFROMSPELL",    "Target","Spellid","","Removes all auras on Target caused by Spellid"},
{"RANGED_MOVEMENT",         "Distance","Angle","","Changes the movement generator type to a ranged type. Note: Default melee type can still be done with this. Specify 0 angle and 0 distance."},
{"RANDOM_PHASE",            "PhaseId1","PhaseId2","PhaseId3","Sets the phase to the id between 3 params*"},
{"RANDOM_PHASE_RANGE",      "PhaseMin","PhaseMax","","Sets the phase to a random id (Phase = PhaseMin + rnd % PhaseMin-PhaseMax). PhaseMax must be greater than PhaseMin."},
{"SUMMON",                  "CreatureID","Target","SummonID","Summons creature (param1) to attack target (param2) at location specified by EventAI_Summons (param3)."},
{"KILLED_MONSTER",          "CreatureID","Target","","Calls KilledMonster (param1) for target of type (param2)"},
{"SET_INST_DATA",           "Field","Data","","Calls ScriptedInstance::SetData with field (param1) and data (param2)"},
{"SET_INST_DATA64",         "Field","Target","","Calls ScriptedInstance::SetData64 with field (param1) and data (param2) target's GUID."},
{"UPDATE_TEMPLATE",         "TemplateId","Team","","Changes the creature to a new creature template of (param1) with team = Alliance if (param2) = false or Horde if (param2) = true"},
{"DIE",                     "","","","Kills the creature"},
{"ZONE_COMBAT_PULSE",       "","","","Places all players within the instance into combat with the creature. Only works in combat and only works inside of instances."},
{"CALL_FOR_HELP",           "Radius","","","Call any friendly out-of-combat creatures in a radius (Param1) to attack current creature's target."},
{"SET_SHEATH",              "Sheath","","","Sets sheath state for a creature (0 = no weapon, 1 = melee weapon, 2 = ranged weapon)."},
{"FORCE_DESPAWN",           "Delay","","","Despawns the creature, if delay = 0 immediate otherwise will despawn after delay time set in Param1 (in ms)."},
{"INVINCIBILITY_HP_LEVEL",  "HP_Level","HP_Percent","","Set min. health level for creature that can be set at damage as flat value or percent from max health"},
{"MOUNT_TO_ENTRY_OR_MODEL", "CreatureEntry","ModelId","","Set mount model from creature_template.entry (Param1) OR explicit modelId (Param2). If (Param1) AND (Param2) are both 0, unmount."},
{"CHANCED_TEXT",            "Chance","-TextId1","-TextId2","Displays by Chance (1..100) the specified -TextId. When -TextId2 is specified, the selection will be randomized. Text types are defined, along with other options for the text, in a table below. Param2 and Param3 needs to be negative."},
{"THROW_AI_EVENT",          "EventType","Radius","","Throws an AIEvent of type (Param1) to nearby friendly Npcs in range of (Param2)"},
{"SET_THROW_MASK",          "EventTypeMask","","","Marks for which AIEvents the npc will throw AIEvents on its own."},
{"SET_STAND_STATE",         "StandState","","","Set the unit stand state (Param1) of the current creature."},
{"CHANGE_MOVEMENT",         "MovementType","WanderDistance","","Change the unit movement type (Param1). If the movement type is Random Movement (1), the WanderDistance (Param2) must be provided."},
};
